version: '3.8'
services:

  #----CLIENT-------
  frontend:
    image: demonstr66/teamwatcher-client
    container_name: client-prod
    restart: always
    expose:
      - 80
    ports:
      - "80:80"
    networks:
      - teamwatcher_network


  # -------------- Server ---------------

  backend:
    image: demonstr66/teamwatcher-server
    container_name: server-prod
    restart: always
    expose:
      - 3000
    ports:
      - "3000:3000"
    networks:
      - teamwatcher_network

# --------------- Networks ---------------
networks:
  teamwatcher_network:
    driver: bridge